# Generated by Django 3.1.3 on 2020-11-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
